name: Deploy to Gitee Pages

on:
  push:
    branches: [ gitee-pages ]
  pull_request:
    branches: [ gitee-pages ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Clean cache
      run: npm run clean
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        gitee-username: ${{ secrets.GITEE_USERNAME }}
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: ${{ secrets.GITEE_REPO }}
        branch: gh-pages
        directory: public
        https: true 